version: '2'
services:
  app:
    image: rentpath/slack-queue-bot:latest
    ports:
      - 4000:4000
    environment:
      - MIX_ENV=prod
      - ECS_ENABLE_TASK_IAM_ROLE=true
    links:
      - redis:redis
    depends_on:
      - redis
    restart: always
    mem_limit: 314572800
  redis:
    image: redis:latest
    ports:
      - 6379
    command: redis-server --appendonly yes
    volumes:
      - ./data:/data
    restart: always
    mem_limit: 26214400
