version: '2'
services:
  app:
    image: alanvoss/slack_queue_bot:latest
    ports:
      - 5000:4000
    environment:
      - MIX_ENV=prod
    links:
      - redis:redis
    depends_on:
      - redis
    mem_limit: 314572800
  redis:
    image: redis:latest
    ports:
      - 6379
    command: redis-server --appendonly yes
    volumes:
      - ./data:/data
    mem_limit: 26214400
