version: '2'
services:
  app:
    build: .
    ports:
      - 127.0.0.1:4000:4000
    environment:
      - MIX_ENV=prod
    links:
      - redis:redis
    depends_on:
      - redis
  redis:
    image: redis:latest
    ports:
      - 127.0.0.1:6379:6379
    command: redis-server --appendonly yes
    volumes:
      - ./data:/data
